apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-default-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name  _;

      location / {
        proxy_pass http://{{.Values.service.serverIP}}:{{.Values.service.serverPort}}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
    }