apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
      - name: {{ .Chart.Name }}-media-volume
        hostPath:
          path: /{{.Values.volumeMountPath}}/{{.Release.Namespace}}/{{ .Chart.Name }}/media
      - name: {{ .Chart.Name }}-music-volume
        hostPath:
          path: /{{.Values.musicVolumeMountPath}}/music
      - name: {{ .Chart.Name }}-users-volume
        hostPath:
          path: /{{.Values.usersVolumeMountPath}}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: {{ .Chart.Name }}-media-volume
          mountPath: /app/media
        - name: {{ .Chart.Name }}-music-volume
          mountPath: /app/music
        - name: {{ .Chart.Name }}-users-volume
          mountPath: /app/users
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        {{- if .Values.config }}
        env:
        {{- range $key, $value := .Values.config }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Chart.Name }}
              key: {{ $key }}
        {{- end }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
      nodeSelector:
          {{- toYaml .Values.deployment.nodeSelector | nindent 12 }}
      affinity:
          {{- toYaml .Values.deployment.affinity | nindent 12 }}
