apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-default-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name  _;

      location /media/ {
        autoindex on;
        add_header Vary Accept-Encoding;
        access_log off;
        alias /media/;
        # add_header Content-disposition "attachment; filename=$1";
      }
    }
