apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
data:
  v: "open-webui:/app/backend/data"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
      - name: {{ .Chart.Name }}-volume
        hostPath:
          path: /{{.Values.volumeMountPath}}/{{.Release.Namespace}}/{{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: {{ .Chart.Name }}-volume
          mountPath: /app/backend/data
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        {{- if .Values.config }}
        env:
        {{- range $key, $value := .Values.config }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Chart.Name }}
              key: {{ $key }}
        {{- end }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
          {{- toYaml .Values.deployment.nodeSelector | nindent 12 }}
